extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- hslogger-1.2.10
- html-1.0.1.2
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.2.0
- parsec-3.1.11
- regex-base-0.93.2
- regex-posix-0.95.2
- semigroups-0.18.3
- sendfile-0.7.9
- stm-2.4.4.1
- syb-0.7
- system-filepath-0.4.13.4
- text-1.2.2.1
- threads-0.5.1.4
- time-compat-0.1.0.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- zlib-0.6.1.2
resolver: ghc-8.0.1
flags: {}
extra-package-dbs: []
packages:
- '.'
