extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1.1
- mtl-2.2.1
- optparse-applicative-0.13.2.0
- regex-base-0.93.2
- regex-posix-0.95.2
- semigroups-0.18.3
- stm-2.4.4.1
- transformers-compat-0.5.1.4
resolver: ghc-8.0.1
flags: {}
extra-package-dbs: []
packages:
- '.'
